// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-q3bgcPYTUI0wMInEO4eoutBN2BV9pcA',
    appId: '1:988369046584:web:5e539754701f8e48676acd',
    messagingSenderId: '988369046584',
    projectId: 'ayurveda-app-63682',
    authDomain: 'ayurveda-app-63682.firebaseapp.com',
    storageBucket: 'ayurveda-app-63682.appspot.com',
    measurementId: 'G-W6QQZV7L1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7qhRNeYXZMWoWF9NtBm0oZGrKTkKZtT4',
    appId: '1:988369046584:android:34b62d764ad2ce87676acd',
    messagingSenderId: '988369046584',
    projectId: 'ayurveda-app-63682',
    storageBucket: 'ayurveda-app-63682.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdHhkh6Q7bIWK8PceChg8rhSFfxrMtLYE',
    appId: '1:988369046584:ios:3a0107cc71bf0665676acd',
    messagingSenderId: '988369046584',
    projectId: 'ayurveda-app-63682',
    storageBucket: 'ayurveda-app-63682.appspot.com',
    iosBundleId: 'com.example.ayurvedaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdHhkh6Q7bIWK8PceChg8rhSFfxrMtLYE',
    appId: '1:988369046584:ios:3a0107cc71bf0665676acd',
    messagingSenderId: '988369046584',
    projectId: 'ayurveda-app-63682',
    storageBucket: 'ayurveda-app-63682.appspot.com',
    iosBundleId: 'com.example.ayurvedaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-q3bgcPYTUI0wMInEO4eoutBN2BV9pcA',
    appId: '1:988369046584:web:a4dcc2ed522ec36e676acd',
    messagingSenderId: '988369046584',
    projectId: 'ayurveda-app-63682',
    authDomain: 'ayurveda-app-63682.firebaseapp.com',
    storageBucket: 'ayurveda-app-63682.appspot.com',
    measurementId: 'G-EX24EKMZ2Y',
  );
}
